[project]
name = "book-scraping-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "google-api-python-client>=2.167.0",
    "requests>=2.32.3",
    "spacy>=3.8.5",
]
